In [ ]:
from criminologia_cdmx.etl import *
from criminologia_cdmx.covariables import *
from criminologia_cdmx.modelos import *
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import geopandas as gpd
import seaborn as sns
import h3
from shapely.geometry import Polygon
import contextily as ctx
import requests
from functools import reduce

In [ ]:
%load_ext autoreload
%autoreload 2

# Procesamiento de datos para estudio sobre robo a repartidores

* Carpetas por colonia y manzana
* datos 911 por colonia

In [ ]:
carpetas = get_carpetas_desde_archivo("datos/descargas/carpetas_fiscalia.csv")
carpetas = agrega_ids_espaciales(carpetas)

## Por Colonias

In [ ]:
fecha_inicio = "01-01-2019"
fecha_fin = "31-12-2019"
delito = ['ROBO A REPARTIDOR SIN VIOLENCIA', 
          'ROBO A REPARTIDOR Y VEHICULO SIN VIOLENCIA']
Y = variable_dependiente(carpetas, 'delito', delito, fecha_inicio, 
                           fecha_fin, nombre_y='Robo a repartidor SV')
Y = Y.rename({'Robo a repartidor SV': 'Robo a repartidor SV 2019'}, axis=1)

fecha_inicio = "01-01-2020"
fecha_fin = "31-12-2020"
delito = ['ROBO A REPARTIDOR SIN VIOLENCIA', 
          'ROBO A REPARTIDOR Y VEHICULO SIN VIOLENCIA']
Y1 = variable_dependiente(carpetas, 'delito', delito, fecha_inicio, 
                           fecha_fin, nombre_y='Robo a repartidor SV')
Y1 = Y1.rename({'Robo a repartidor SV': 'Robo a repartidor SV 2020'}, axis=1)

fecha_inicio = "01-01-2021"
fecha_fin = "31-12-2021"
delito = ['ROBO A REPARTIDOR SIN VIOLENCIA', 
          'ROBO A REPARTIDOR Y VEHICULO SIN VIOLENCIA']
Y2 = variable_dependiente(carpetas, 'delito', delito, fecha_inicio, 
                           fecha_fin, nombre_y='Robo a repartidor SV')
Y2 = Y2.rename({'Robo a repartidor SV': 'Robo a repartidor SV 2021'}, axis=1)
total_sv = reduce(lambda left, right: left.merge(right, on='colonia_cve'), [Y, Y1, Y2])
total_sv

,colonia_cve,Robo a repartidor SV 2019,Robo a repartidor SV 2020,Robo a repartidor SV 2021
0,32,0.0,0.0,0.0
1,619,0.0,0.0,0.0
2,1792,0.0,0.0,0.0
3,1774,0.0,0.0,0.0
4,583,0.0,0.0,0.0
...,...,...,...,...
1819,1731,0.0,1.0,0.0
1820,1801,0.0,0.0,0.0
1821,1799,0.0,0.0,0.0
1822,1800,0.0,0.0,0.0
1823,1824,0.0,0.0,0.0

In [ ]:
fecha_inicio = "01-01-2019"
fecha_fin = "31-12-2019"
delito = ['ROBO A REPARTIDOR CON VIOLENCIA', 
          'ROBO A REPARTIDOR Y VEHICULO CON VIOLENCIA']
Y = variable_dependiente(carpetas, 'delito', delito, fecha_inicio, 
                           fecha_fin, nombre_y='Robo a repartidor CV')
Y = Y.rename({'Robo a repartidor CV': 'Robo a repartidor CV 2019'}, axis=1)

fecha_inicio = "01-01-2020"
fecha_fin = "31-12-2020"
delito = ['ROBO A REPARTIDOR CON VIOLENCIA', 
          'ROBO A REPARTIDOR Y VEHICULO CON VIOLENCIA']
Y1 = variable_dependiente(carpetas, 'delito', delito, fecha_inicio, 
                           fecha_fin, nombre_y='Robo a repartidor CV')
Y1 = Y1.rename({'Robo a repartidor CV': 'Robo a repartidor CV 2020'}, axis=1)

fecha_inicio = "01-01-2021"
fecha_fin = "31-12-2021"
delito = ['ROBO A REPARTIDOR CON VIOLENCIA', 
          'ROBO A REPARTIDOR Y VEHICULO CON VIOLENCIA']
Y2 = variable_dependiente(carpetas, 'delito', delito, fecha_inicio, 
                           fecha_fin, nombre_y='Robo a repartidor CV')
Y2 = Y2.rename({'Robo a repartidor CV': 'Robo a repartidor CV 2021'}, axis=1)

total_cv = reduce(lambda left, right: left.merge(right, on='colonia_cve'), [Y, Y1, Y2])
total_cv

,colonia_cve,Robo a repartidor CV 2019,Robo a repartidor CV 2020,Robo a repartidor CV 2021
0,32,0.0,0.0,0.0
1,619,0.0,0.0,0.0
2,1792,1.0,0.0,0.0
3,1774,0.0,0.0,0.0
4,583,0.0,1.0,0.0
...,...,...,...,...
1819,1731,7.0,0.0,12.0
1820,1801,0.0,0.0,0.0
1821,1799,1.0,2.0,5.0
1822,1800,7.0,2.0,1.0
1823,1824,0.0,0.0,0.0

In [ ]:
total = total_sv.merge(total_cv, on='colonia_cve')
total

,colonia_cve,Robo a repartidor SV 2019,Robo a repartidor SV 2020,Robo a repartidor SV 2021,Robo a repartidor CV 2019,Robo a repartidor CV 2020,Robo a repartidor CV 2021
0,32,0.0,0.0,0.0,0.0,0.0,0.0
1,619,0.0,0.0,0.0,0.0,0.0,0.0
2,1792,0.0,0.0,0.0,1.0,0.0,0.0
3,1774,0.0,0.0,0.0,0.0,0.0,0.0
4,583,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...
1819,1731,0.0,1.0,0.0,7.0,0.0,12.0
1820,1801,0.0,0.0,0.0,0.0,0.0,0.0
1821,1799,0.0,0.0,0.0,1.0,2.0,5.0
1822,1800,0.0,0.0,0.0,7.0,2.0,1.0
1823,1824,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
total.to_csv("datos/descargas/robo_repartidor_colonias_19-21.csv", index=False)

## Por manzanas

In [ ]:
fecha_inicio = "01-01-2019"
fecha_fin = "31-12-2019"
delito = ['ROBO A REPARTIDOR SIN VIOLENCIA', 
          'ROBO A REPARTIDOR Y VEHICULO SIN VIOLENCIA']
Y = variable_dependiente(carpetas, 'delito', delito, fecha_inicio, 
                         fecha_fin, agregacion='manzanas', nombre_y='Robo a repartidor SV')
Y = Y.rename({'Robo a repartidor SV': 'Robo a repartidor SV 2019'}, axis=1)

fecha_inicio = "01-01-2020"
fecha_fin = "31-12-2020"
delito = ['ROBO A REPARTIDOR SIN VIOLENCIA', 
          'ROBO A REPARTIDOR Y VEHICULO SIN VIOLENCIA']
Y1 = variable_dependiente(carpetas, 'delito', delito, fecha_inicio,  
                          fecha_fin, agregacion='manzanas', nombre_y='Robo a repartidor SV')
Y1 = Y1.rename({'Robo a repartidor SV': 'Robo a repartidor SV 2020'}, axis=1)

fecha_inicio = "01-01-2021"
fecha_fin = "31-12-2021"
delito = ['ROBO A REPARTIDOR SIN VIOLENCIA', 
          'ROBO A REPARTIDOR Y VEHICULO SIN VIOLENCIA']
Y2 = variable_dependiente(carpetas, 'delito', delito, fecha_inicio, 
                           fecha_fin, agregacion='manzanas', nombre_y='Robo a repartidor SV')
Y2 = Y2.rename({'Robo a repartidor SV': 'Robo a repartidor SV 2021'}, axis=1)
total_sv = reduce(lambda left, right: left.merge(right, on='manzana_cvegeo'), [Y, Y1, Y2])
total_sv

,manzana_cvegeo,Robo a repartidor SV 2019,Robo a repartidor SV 2020,Robo a repartidor SV 2021
0,0901000010898031,0.0,0.0,0.0
1,0901000012269024,0.0,0.0,0.0
2,0901000011472068,0.0,0.0,0.0
3,0901000011824024,0.0,0.0,0.0
4,0901000012377004,0.0,0.0,0.0
...,...,...,...,...
66314,0900700015376020,0.0,0.0,0.0
66315,0900700015376021,0.0,0.0,0.0
66316,0900700013045056,0.0,0.0,0.0
66317,0900700013045032,0.0,0.0,0.0
66318,0900700011848016,0.0,0.0,0.0

In [ ]:
fecha_inicio = "01-01-2019"
fecha_fin = "31-12-2019"
delito = ['ROBO A REPARTIDOR CON VIOLENCIA', 
          'ROBO A REPARTIDOR Y VEHICULO CON VIOLENCIA']
Y = variable_dependiente(carpetas, 'delito', delito, fecha_inicio, 
                           fecha_fin, agregacion='manzanas', nombre_y='Robo a repartidor CV')
Y = Y.rename({'Robo a repartidor CV': 'Robo a repartidor CV 2019'}, axis=1)

fecha_inicio = "01-01-2020"
fecha_fin = "31-12-2020"
delito = ['ROBO A REPARTIDOR CON VIOLENCIA', 
          'ROBO A REPARTIDOR Y VEHICULO CON VIOLENCIA']
Y1 = variable_dependiente(carpetas, 'delito', delito, fecha_inicio, 
                           fecha_fin, agregacion='manzanas', nombre_y='Robo a repartidor CV')
Y1 = Y1.rename({'Robo a repartidor CV': 'Robo a repartidor CV 2020'}, axis=1)

fecha_inicio = "01-01-2021"
fecha_fin = "31-12-2021"
delito = ['ROBO A REPARTIDOR CON VIOLENCIA', 
          'ROBO A REPARTIDOR Y VEHICULO CON VIOLENCIA']
Y2 = variable_dependiente(carpetas, 'delito', delito, fecha_inicio, 
                           fecha_fin, agregacion='manzanas', nombre_y='Robo a repartidor CV')
Y2 = Y2.rename({'Robo a repartidor CV': 'Robo a repartidor CV 2021'}, axis=1)

total_cv = reduce(lambda left, right: left.merge(right, on='manzana_cvegeo'), [Y, Y1, Y2])
total_cv

,manzana_cvegeo,Robo a repartidor CV 2019,Robo a repartidor CV 2020,Robo a repartidor CV 2021
0,0901000010898031,0.0,0.0,0.0
1,0901000012269024,0.0,0.0,0.0
2,0901000011472068,0.0,0.0,0.0
3,0901000011824024,0.0,0.0,0.0
4,0901000012377004,0.0,0.0,0.0
...,...,...,...,...
66314,0900700015376020,0.0,0.0,0.0
66315,0900700015376021,0.0,0.0,0.0
66316,0900700013045056,0.0,0.0,0.0
66317,0900700013045032,0.0,1.0,0.0
66318,0900700011848016,0.0,0.0,0.0

In [ ]:
total = total_sv.merge(total_cv, on='manzana_cvegeo')
total

,manzana_cvegeo,Robo a repartidor SV 2019,Robo a repartidor SV 2020,Robo a repartidor SV 2021,Robo a repartidor CV 2019,Robo a repartidor CV 2020,Robo a repartidor CV 2021
0,0901000010898031,0.0,0.0,0.0,0.0,0.0,0.0
1,0901000012269024,0.0,0.0,0.0,0.0,0.0,0.0
2,0901000011472068,0.0,0.0,0.0,0.0,0.0,0.0
3,0901000011824024,0.0,0.0,0.0,0.0,0.0,0.0
4,0901000012377004,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...
66370,0900700015376020,0.0,0.0,0.0,0.0,0.0,0.0
66371,0900700015376021,0.0,0.0,0.0,0.0,0.0,0.0
66372,0900700013045056,0.0,0.0,0.0,0.0,0.0,0.0
66373,0900700013045032,0.0,0.0,0.0,0.0,1.0,0.0
66374,0900700011848016,0.0,0.0,0.0,0.0,0.0,0.0

## Agregar id de colonia al de manzana

In [ ]:
manzanas_colonias = (gpd
                    .read_file("datos/descargas/manzanas_identificadores.gpkg", layer="manzanas")
                    .rename({"CVEGEO": 'manzana_cvegeo'}, axis=1))
manzanas_colonias.head()

,manzana_cvegeo,CVE_ENT,CVE_MUN,CVE_LOC,CVE_AGEB,CVE_MZA,AMBITO,TIPOMZA,colonia_cve,colonia_nombre,cuadrante_id,geometry
0,0901000010898031,09,010,0001,0898,031,Urbana,Típica,1119,HERON PROAL,017,"POLYGON ((2790204.135 820779.247, 2790125.593 ..."
1,0901000012269024,09,010,0001,2269,024,Urbana,Típica,1082,LOMAS DE TARANGO,014,"POLYGON ((2791387.916 821465.156, 2791376.215 ..."
2,0901000011472068,09,010,0001,1472,068,Urbana,Típica,1030,GRAL A ROSALES,011,"POLYGON ((2788494.355 822775.106, 2788478.422 ..."
3,0901000011824024,09,010,0001,1824,024,Urbana,Típica,1135,SAN CLEMENTE,0110,"POLYGON ((2790870.494 819456.298, 2790862.256 ..."
4,0901000012377004,09,010,0001,2377,004,Urbana,Típica,1081,HOGAR Y REDENCION,018,"POLYGON ((2792111.138 821977.886, 2792115.437 ..."

In [ ]:
total.describe()

,Robo a repartidor SV 2019,Robo a repartidor SV 2020,Robo a repartidor SV 2021,Robo a repartidor CV 2019,Robo a repartidor CV 2020,Robo a repartidor CV 2021
count,66375.000000,66375.000000,66375.000000,66375.000000,66375.000000,66375.0000
mean,0.010531,0.007879,0.007518,0.040919,0.027028,0.0218
std,0.187507,0.108743,0.098138,0.234979,0.178191,0.1585
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000
75%,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000
max,34.000000,10.000000,6.000000,13.000000,6.000000,5.0000

In [ ]:
total = total.merge(manzanas_colonias[['manzana_cvegeo', 'colonia_cve']], on='manzana_cvegeo')
total.to_csv("datos/descargas/robo_repartidor_manzanas_19-21.csv", index=False)

In [ ]:
manzanas_colonias.TIPOMZA.unique()

array(['Típica', 'Contenida', 'Edificio-Manzana', 'Contenedora',
       'Bajo Puente', 'Camellón', 'Atípica', 'Parque o Jardín',
       'Glorieta', 'Económica'], dtype=object)

## Datos 911

In [ ]:
datos_911 = get_datos_911()
datos_911

El archivo ya está descargado.

,folio,incidente_c4,fecha_creacion,hora_creacion,mes_creacion,año_creacion,fecha_cierre,mes_cierre,año_cierre,hora_cierre,...,codigo_cierre,clas_con_f_alarma,delegacion_cierre,manzana,longitud_centroide,latitud_centroide,geometry,colonia_cve,colonia_nombre,cuadrante_id
0,C5/200702/07369,Lesionado-Caída,2020-07-02,21:25:59,Julio,2020.0,2020-07-02,Julio,2020.0,21:30:35,...,Duplicado,URGENCIAS MEDICAS,GUSTAVO A. MADERO,0900500012907021,-99.09506,19.48655,POINT (-99.09506 19.48655),662,SALVADOR DIAZ MIRON,015
6657,C5/200703/03163,Médicos-Convulsiones,2020-07-03,11:46:51,Julio,2020.0,2020-07-03,Julio,2020.0,11:52:46,...,Duplicado,URGENCIAS MEDICAS,GUSTAVO A. MADERO,0900500012907021,-99.09506,19.48655,POINT (-99.09506 19.48655),662,SALVADOR DIAZ MIRON,015
25901,C5/200712/00975,Disturbio-Fiestas,2020-07-12,01:39:46,Julio,2020.0,2020-07-12,Julio,2020.0,01:42:46,...,Duplicado,FALTA CÍVICA,GUSTAVO A. MADERO,0900500012907021,-99.09506,19.48655,POINT (-99.09506 19.48655),662,SALVADOR DIAZ MIRON,015
45484,C5/200709/04377,Disturbio-Escándalo,2020-07-09,16:44:01,Julio,2020.0,2020-07-09,Julio,2020.0,16:53:41,...,Negativo,FALTA CÍVICA,GUSTAVO A. MADERO,0900500012907021,-99.09506,19.48655,POINT (-99.09506 19.48655),662,SALVADOR DIAZ MIRON,015
48174,C5/200717/04329,Lesionado-Por Golpes-Agresión,2020-07-17,15:32:46,Julio,2020.0,2020-07-17,Julio,2020.0,15:49:46,...,Negativo,URGENCIAS MEDICAS,GUSTAVO A. MADERO,0900500012907021,-99.09506,19.48655,POINT (-99.09506 19.48655),662,SALVADOR DIAZ MIRON,015
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3681081,C5/190718/02975,Cadáver-Natural,2019-07-18,11:51:59,Julio,2019.0,2019-07-18,Julio,2019.0,13:14:20,...,Afirmativo,EMERGENCIA,COYOACAN,0900300011730006,-99.133123,19.314774,POINT (-99.13312 19.31477),1232,LOS ROBLES (FRACC),0213
3703218,C5/191229/06232,Lesionado-Caída,2019-12-29,18:22:55,Diciembre,2019.0,2019-12-29,Diciembre,2019.0,18:44:00,...,Duplicado,URGENCIAS MEDICAS,MILPA ALTA,0900900170365011,-99.011308,19.194389,POINT (-99.01131 19.19439),1548,SAN AGUSTIN OHTENCO (PBLO),023
3704538,C5/191229/05845,Lesionado-Caída,2019-12-29,17:28:25,Diciembre,2019.0,2019-12-29,Diciembre,2019.0,17:59:58,...,Afirmativo,URGENCIAS MEDICAS,MILPA ALTA,0900900170365011,-99.011308,19.194389,POINT (-99.01131 19.19439),1548,SAN AGUSTIN OHTENCO (PBLO),023
3706709,C5/190725/04837,Daños por Fenómeno Natural o Tercero-Caída de ...,2019-07-25,16:20:31,Julio,2019.0,2019-07-25,Julio,2019.0,16:29:21,...,Duplicado,SERVICIO,ALVARO OBREGON,0901000011148032,-99.259052,19.338943,POINT (-99.25905 19.33894),1122,VILLA VERDUN,013
3707946,C5/190725/04806,Daños por Fenómeno Natural o Tercero-Caída de ...,2019-07-25,16:17:41,Julio,2019.0,2019-07-25,Julio,2019.0,18:14:56,...,Afirmativo,SERVICIO,ALVARO OBREGON,0901000011148032,-99.259052,19.338943,POINT (-99.25905 19.33894),1122,VILLA VERDUN,013

Necesitamos únicamente las llamadas que corresponden a un delito y cuyo código de cierre sea afirmativo

In [ ]:
datos_911.clas_con_f_alarma.unique()

array(['URGENCIAS MEDICAS', 'FALTA CÍVICA', 'DELITO', 'SERVICIO',
       'EMERGENCIA', 'FALTA CÃ\x8dVICA', 'FALSA ALARMA'], dtype=object)

In [ ]:
datos_911.codigo_cierre.unique()

array(['Duplicado', 'Negativo', 'Afirmativo', 'N', 'A', 'D', 'Otros',
       'Falso', 'Informativo', 'I'], dtype=object)

In [ ]:
datos_911 = (datos_911
             .loc[(datos_911.clas_con_f_alarma == 'DELITO') & (datos_911.codigo_cierre.isin((['Afirmativo', 'A'])))])
datos_911

,folio,incidente_c4,fecha_creacion,hora_creacion,mes_creacion,año_creacion,fecha_cierre,mes_cierre,año_cierre,hora_cierre,...,codigo_cierre,clas_con_f_alarma,delegacion_cierre,manzana,longitud_centroide,latitud_centroide,geometry,colonia_cve,colonia_nombre,cuadrante_id
57708,C5/200726/05788,Agresión-Casa Habitación,2020-07-26,15:11:10,Julio,2020.0,2020-07-26,Julio,2020.0,15:47:43,...,Afirmativo,DELITO,GUSTAVO A. MADERO,0900500012907021,-99.09506,19.48655,POINT (-99.09506 19.48655),662,SALVADOR DIAZ MIRON,015
133082,C5/200818/05230,Disturbio-Riña,2020-08-18,19:07:51,Agosto,2020.0,2020-08-18,Agosto,2020.0,19:37:22,...,Afirmativo,DELITO,GUSTAVO A. MADERO,0900500012907021,-99.09506,19.48655,POINT (-99.09506 19.48655),662,SALVADOR DIAZ MIRON,015
266474,C5/200908/05808,Disturbio-Quema de Pirotecnia,2020-09-08,20:10:58,Septiembre,2020.0,2020-09-08,Septiembre,2020.0,20:20:31,...,Afirmativo,DELITO,GUSTAVO A. MADERO,0900500012907021,-99.09506,19.48655,POINT (-99.09506 19.48655),662,SALVADOR DIAZ MIRON,015
869990,C5/20210420/00226,Disturbio-Disparos,2021-04-20,01:20:37,Abril,NaN,2021-04-20,Abril,NaN,02:12:25,...,A,DELITO,GUSTAVO A. MADERO,9.01E+14,-99.09506,19.48655,POINT (-99.09506 19.48655),662,SALVADOR DIAZ MIRON,015
922761,C5/20210429/00912,Agresión-Persona,2021-04-29,07:51:15,Abril,NaN,2021-04-29,Abril,NaN,08:14:16,...,A,DELITO,GUSTAVO A. MADERO,9.01E+14,-99.09506,19.48655,POINT (-99.09506 19.48655),662,SALVADOR DIAZ MIRON,015
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3037702,C5/190502/03463,Disturbio-Riña,2019-05-02,12:27:20,Mayo,2019.0,2019-05-02,Mayo,2019.0,12:52:19,...,Afirmativo,DELITO,ALVARO OBREGON,0901000010135044,-99.192006,19.393222,POINT (-99.19201 19.39322),968,TORRES SAN PEDRO (U HAB),015
3095553,C5/191110/06093,Agresión-Negocio,2019-11-10,14:57:33,Noviembre,2019.0,2019-11-10,Noviembre,2019.0,20:44:44,...,Afirmativo,DELITO,IZTAPALAPA,090070001013A001,-99.056387,19.386181,POINT (-99.05639 19.38618),419,"EJTO CONSTITUCIONALISTA, SUPERMANZANA II ( U HAB)",0119
3315326,C5/190906/05658,Agresión-Persona,2019-09-06,17:23:46,Septiembre,2019.0,2019-09-06,Septiembre,2019.0,18:32:30,...,Afirmativo,DELITO,TLALPAN,0901200010197008,-99.133347,19.305269,POINT (-99.13335 19.30527),497,JARDINES COAPA-BELISARIO DOMINGUEZ,042
3262843,C5/190919/05385,Disturbio-Disparos,2019-09-19,14:14:38,Septiembre,2019.0,2019-09-19,Septiembre,2019.0,14:38:25,...,Afirmativo,DELITO,TLALPAN,0901200262403011,-99.18281800000001,19.21452,POINT (-99.18282 19.21452),1701,JARDINES DE SAN JUAN,045
3292317,C5/190914/06338,Agresión-Persona,2019-09-14,16:53:21,Septiembre,2019.0,2019-09-14,Septiembre,2019.0,17:21:39,...,Afirmativo,DELITO,ALVARO OBREGON,0901000010667038,-99.235217,19.366178,POINT (-99.23522 19.36618),1079,GARCIMARRERO REACOMODO,015

In [ ]:
def agrega_911(datos, columna_y, valores_y, 
                           fecha_inicio, fecha_fin, 
                           agregacion='colonias',
                           filtro = 'Afirmativos',
                           nombre_y=None):
    """ Regresa un DataFrame con la variable independicente agregada entre fecha_inicio y fecha_fin
        en las unidades requeridas.
        
        Args:
            datos (DataFrame): carpetas/victimas con ids espaciales y categorías de usuario
            columna_y (str): Nombre de la columna en donde vienen los incidentes de valor_y
            valores_y (list): delitos o categorías a utilizar como Y
            fecha_inicio (str): fecha inicial para agregar delitos "d-m-Y"
            fecha_fin (str): fecha final para agregar delitos "d-m-Y"
            agregacion (str): colonias/cuadrantes/manzanas. Eventualmente debe recibir 
                              agregaciones arbitrarias (opcional)
            nombre_y (str): Nombre para la columna con la variable dependiente 
                           (opcional, si se omite se concatenan los nombres de valores_y).
    """
    fecha_inicio = pd.to_datetime(fecha_inicio, dayfirst=True)
    fecha_fin = pd.to_datetime(fecha_fin, dayfirst=True)
    datos = datos.loc[datos['fecha_creacion'].between(fecha_inicio, fecha_fin)]
    if filtro == 'Afirmativos':
        datos = datos.loc[datos['codigo_cierre'].isin(['Afirmativo', 'A'])]
    datos = datos.loc[datos[columna_y].isin(valores_y)]
    if agregacion == 'colonias':
        columna_agrega = 'colonia_cve'
        layer = 'colonias'
    elif agregacion == 'cuadrantes':
        columna_agrega = 'cuadrante_id'
        layer = 'cuadrantes'
    elif agregacion == 'manzanas':
        try:
            assert 'manzana_cvegeo' in datos.columns
        except AssertionError:
            print("Para usar la agregación por manzanas primero \
                  debes agregar el identificador correspondiente")
            raise
        columna_agrega = 'manzana_cvegeo'
    else:
        raise ValueError("unidades debe ser 'colonias' o 'cuadrantes'")
    datos = datos.groupby(columna_agrega).size()
    if nombre_y is not None:
        datos.name = nombre_y
    else:
        datos.name = " ".join(valores_y)
    if agregacion in ('colonias', 'cuadrantes'):
        unidades = gpd.read_file("datos/criminologia_capas.gpkg", layer=layer)
    else:
        unidades = (gpd
                    .read_file("datos/descargas/manzanas_identificadores.gpkg", layer="manzanas")
                    .rename({"CVEGEO": columna_agrega}, axis=1))
        
    
    datos = unidades[[columna_agrega]].merge(datos, on=columna_agrega, how='left').fillna(0)
    return datos

In [ ]:
fecha_inicio = "01-01-2019"
fecha_fin = "31-12-2019"
d_19 = agrega_911(datos_911, 'clas_con_f_alarma', 
                  ['DELITO'], fecha_inicio, fecha_fin, 
                  agregacion='colonias', nombre_y='Incidentes 2019')
d_19

      colonia_cve  Incidentes 2019
0              32              0.0
1             619             45.0
2            1792              3.0
3            1774              2.0
4             583             54.0
...           ...              ...
1819         1731             51.0
1820         1801              0.0
1821         1799             18.0
1822         1800             24.0
1823         1824              8.0

[1824 rows x 2 columns]

In [ ]:
fecha_inicio = "01-01-2020"
fecha_fin = "31-12-2020"
d_20 = agrega_911(datos_911, 'clas_con_f_alarma', 
                  ['DELITO'], fecha_inicio, fecha_fin, 
                  agregacion='colonias', nombre_y='Incidentes 2020')
fecha_inicio = "01-01-2021"
fecha_fin = "31-12-2021"
d_21 = agrega_911(datos_911, 'clas_con_f_alarma', 
                  ['DELITO'], fecha_inicio, fecha_fin, 
                  agregacion='colonias', nombre_y='Incidentes 2021')
total_incidentes = reduce(lambda left, right: left.merge(right, on='colonia_cve'), [d_19, d_20, d_21])
total_incidentes

      colonia_cve  Incidentes 2019  Incidentes 2020  Incidentes 2021
0              32              0.0              0.0              0.0
1             619             45.0             17.0             30.0
2            1792              3.0              2.0              5.0
3            1774              2.0              2.0              1.0
4             583             54.0             52.0             52.0
...           ...              ...              ...              ...
1819         1731             51.0             56.0             68.0
1820         1801              0.0              0.0              0.0
1821         1799             18.0             15.0             20.0
1822         1800             24.0             17.0             17.0
1823         1824              8.0              6.0              8.0

[1824 rows x 4 columns]

In [ ]:
total_incidentes.to_csv("datos/salidas/incidentes_911_colonias_19_21.csv", index=False)